### PR TITLE
fix/110782 -> master

### PR DESCRIPTION
**Pull request by murilobarr0s**
[AB#110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)

### CODE REVIEW

**Comment by luizhpriotto** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 110781

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by luizhpriotto** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 110781

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Review by GabrielVedolin — APPROVED** [review]

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)

**Pull request merged**
