### PR TITLE
Feature/115973

### PR DESCRIPTION
**Pull request by thiiagofernando**
[AB#121480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121480)
[AB#115973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115973)

### CODE REVIEW

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Task 115973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115973)

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Task 115973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115973)

**Review by Jailsvs — APPROVED** [review]

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Task 121480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121480)
- [Task 115973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115973)

**Comment by luizhpriotto** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Task 121480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121480)
- [Task 115973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115973)

**Review by Jailsvs — APPROVED** [review]

**Pull request merged**
